# SITE CONFIGURATION - https://www.photopea.com/#irq8R0xui
baseurl: ""
url: ""

# THEME-SPECIFIC CONFIGURATION
title: Eskap                                    # site's title
description: "Trouver les escapes games Ã  proximitÃ©"      # used by search engines
avatar: assets/img/eskap.png                         # Empty for no avatar in navbar
favicon: assets/favicon.ico                             # Icon displayed in the tab

# Header and footer text
header_text: Blog du projet Eskap  # Change Blog header text
header_feature_image: assets/img/pexels/eskap_background.png
footer_text: >
  Eskap est une application mobile vous permettant de trouver  les Escape Game les plus proches de chez vous ðŸ“.

# Blog
excerpt: true                                           # Or "truncate" (first 250 characters), "false" to disable
post_navigation: true
# color_image: /assets/img/lineart.png                    # A bit transparent for color posts.

# Features
# More in the _data folder for social icons, share buttons, author and language
# For layout customization, go to the "_sass > base" folder, and check "_variables.scss"
katex: true                                             # Enable if using math markup
google_analytics:                                       # Tracking ID, e.g. "UA-000000-01"
cookie_consent: false                                   # To respect the usage of cookies
disqus_shortname:                                       # Your discus shortname for comments

# PAGINATION
paginate: 5
paginate_path: "/blog/page:num"

# BUILD SETTINGS
plugins: [jekyll-paginate, jekyll-seo-tag, jekyll-feed]
exclude: [".jekyll-cache", ".idea", "vendor/*", "assets/node_modules"]

# theme: type-on-strap                                  # if using the theme as a jekyll theme gem
# remote_theme: sylhare/Type-on-Strap                     # If using as a remote_theme in github